config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  # users
  resources :categories, only: [:show]
  resources :products, only: [:index, :show]

  resources :categories, only: [:show] do
    get 'filter_products', on: :member
  end  

  get "admin" => "admin#index"

end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
end

app/controllers/admin/stocks_controller.rb
class Admin::StocksController < AdminController
  before_action :set_admin_stock, only: %i[ show edit update destroy ]

  # GET /admin/stocks or /admin/stocks.json
  def index
    @admin_stocks = Stock.where(product_id: params[:product_id])
  end

  # GET /admin/stocks/1 or /admin/stocks/1.json
  def show
  end

  # GET /admin/stocks/new
  def new
    @product = Product.find(params[:product_id])
    @admin_stock = Stock.new
  end

  # GET /admin/stocks/1/edit
  def edit
    @product = Product.find(params[:product_id])
    @admin_stock = Stock.find(params[:id])
  end

  # POST /admin/stocks or /admin/stocks.json
  def create
    @product = Product.find(params[:product_id])
    @admin_stock = @product.stocks.new(admin_stock_params)

    respond_to do |format|
      if @admin_stock.save
        format.html { redirect_to admin_product_stock_url(@product, @admin_stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @admin_stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/stocks/1 or /admin/stocks/1.json
  def update
    respond_to do |format|
      if @admin_stock.update(admin_stock_params)
        format.html { redirect_to admin_product_stock_url(@admin_stock.product, @admin_stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/stocks/1 or /admin/stocks/1.json
  def destroy
    @admin_stock.destroy!

    respond_to do |format|
      format.html { redirect_to admin_product_stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_stock
      @admin_stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_stock_params
      params.require(:stock).permit(:size, :amount)
    end
end

app/helpers/admin/stocks_helper.rb
module Admin::StocksHelper
end

app/views/admin/stocks/_form.html.erb
<%= form_with(model: [:admin, @product, admin_stock]) do |form| %>
  <% if admin_stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_stock.errors.count, "error") %> prohibited this admin_stock from being saved:</h2>

      <ul>
        <% admin_stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.text_field :size %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
  <p>
    <strong>Size:</strong>
    <%= stock.size %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= stock.amount %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= stock.product_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this stock", [:admin, stock.product, stock] %>
    <%= link_to "Edit this stock", edit_admin_product_stock_path(stock.product, stock) %>
    <hr>
  <% end %>

</div>

app/views/admin/stocks/edit.html.erb
<% content_for :title, "Editing stock" %>

<h1>Editing stock</h1>

<%= render "form", admin_stock: @admin_stock %>

<br>

<div>
  <%= link_to "Show this stock", [:admin, @product, @admin_stock] %> |
  <%= link_to "Back to stocks", admin_product_stocks_path %>
</div>

app/views/admin/stocks/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Stocks" %>

<h1>Stocks</h1>

<div id="admin_stocks">
  <% @admin_stocks.each do |admin_stock| %>
    <%= render admin_stock %>    
  <% end %>
</div>

<%= link_to "New stock", new_admin_product_stock_path %>

app/views/admin/stocks/new.html.erb
<% content_for :title, "New stock" %>

<h1>New stock</h1>

<%= render "form", admin_stock: @admin_stock %>

<br>

<div>
  <%= link_to "Back to stocks", admin_product_stocks_path %>
</div>

app/views/admin/stocks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_stock %>

<div>
  <%= link_to "Edit this stock", edit_admin_product_stock_path(@admin_stock) %> |
  <%= link_to "Back to stocks", admin_product_stocks_path %>

  <%= button_to "Destroy this stock", admin_product_stock_path(@admin_stock), method: :delete %>
</div>