config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  # users
  resources :categories, only: [:show]
  resources :products, only: [:index, :show]

  resources :categories, only: [:show] do
    get 'filter_products', on: :member
  end  

  get "admin" => "admin#index"

end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
  
  belongs_to :category
  has_many :stocks
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_admin_product, only: %i[ show edit update destroy ]

  # GET /admin/products or /admin/products.json
  def index
    @admin_products = Product.all
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products or /admin/products.json
  def create
    @admin_product = Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_product_url(@admin_product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    @admin_product = Product.find(params[:id])
    if @admin_product.update(admin_product_params.reject { |k| k["images"] })
      if admin_product_params["images"]
        admin_product_params["images"].each do |image|
          @admin_product.images.attach(image)
        end
      end
      redirect_to admin_products_path, notice: "Product updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    @admin_product.destroy!

    respond_to do |format|
      format.html { redirect_to admin_products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_product_params
      params.require(:product).permit(:name, :description, :price, :category_id, :active, images: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all

        # Filtering based on price
      if params[:price].present?
        @products = @products.where("price <= ?", params[:price])
      end
    end

    def show
      @product = Product.find(params[:id])      
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, admin_product]) do |form| %>
  <% if admin_product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
        <% admin_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <% if admin_product.images.any? %>
      <% admin_product.images.each do |image| %>
        <%= image_tag image, style: "width: 100px; height: 100px" %>
      <% end %>
    <% end %>
    <%= form.label :images, style: "display: block" %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.collection_select :category_id, Category.order(:name), :id, :name, id: "category" %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <% unless admin_product.new_record? %>
    <div>
      <%= link_to "Product stock", admin_product_stocks_path(admin_product) %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <% if product.images.any? %>
      <% product.images.each do |image| %>
        <%= image_tag image, style: "width: 100px; height: 100px" %>
      <% end %>
    <% end %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category_id %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= product.active %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "show this product", [:admin, product] %>
    <%= link_to "Edit this product", edit_admin_product_path(product) %>
  <% end %>

</div>

app/views/admin/products/edit.html.erb
<% content_for :title, "Editing product" %>

<h1>Editing product</h1>

<%= render "form", admin_product: @admin_product %>

<br>

<div>
  <%= link_to "Show this product", [:admin, @admin_product] %> |
  <%= link_to "Back to products", admin_products_path %>
</div>

app/views/admin/products/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Products" %>

<h1>Products</h1>

<%= link_to "New product", new_admin_product_path %>

<div>
  <table>
    <thead>
      <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @admin_products.each do |admin_product| %>
      <tr>
        <td>
          <%= admin_product.images.any? ? image_tag(admin_product.images.first, style: "width: 50px; height: 50px") : image_tag("https://via.placeholder.com/50") %>
        </td>
        <td>
          <%= link_to admin_product.name, edit_admin_product_path(admin_product) %>
        </td>
        <td>
          <%= admin_product.description %>
        </td>
        <td>
          Ksh <%= admin_product.price %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/products/new.html.erb
<% content_for :title, "New product" %>

<h1>New product</h1>

<%= render "form", admin_product: @admin_product %>

<br>

<div>
  <%= link_to "Back to products", admin_products_path %>
</div>

app/views/admin/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_product %>

<div>
  <%= link_to "Edit this product", edit_admin_product_path(@admin_product) %> |
  <%= link_to "Back to products", admin_products_path %>

  <%= button_to "Destroy this product", admin_product_path(@admin_product), method: :delete %>
</div>