config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  # users
  resources :categories, only: [:show]
  resources :products, only: [:index, :show]

  resources :categories, only: [:show] do
    get 'filter_products', on: :member
  end  

  get "admin" => "admin#index"

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Plantt" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="admin">
        <nav class="sidebar">
            <div>
                <div class="logo-section">
                    <div class="logo">
                        <div class="one"></div>
                        <div class="two"></div>
                        <div class="three"></div>
                        <div class="four"></div>
                    </div>
                    <h1 style="color: green; line-height: 50px; font-size: 50px; font-weight: 300;">Plantt</h1>
                </div>
                <ul class="links">
                    <li>
                        <%= link_to admin_path do %>
                            <i class="fas fa-tachometer-alt"></i>
                            <span>Dashboard</span>
                        <% end %>
                    </li>
                    <li>
                        <i class="fas fa-users"></i>
                        <span>Users</span>
                    </li>
                    <li>
                        <%= link_to admin_products_path do %>
                            <i class="fas fa-box"></i>
                            <span>Products</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to admin_categories_path do %>
                            <i class="fas fa-list"></i>
                            <span>Category</span>
                        <% end %>
                    </li>
                    <li>
                        <i class="fas fa-shopping-cart"></i>
                        <span>Orders</span>
                    </li>
                    <li>
                        <i class="fas fa-sign-out"></i>
                        <span>Sign out</span>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="content">
            <%= yield %>
        </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Plantt" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <main>
      <%= yield %>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>